const workTypeOptions = [
    {value: "diplom", label: "Дипломная работа"},
    {value: "diplompro", label: "Дипломный проект"},
    {value: "magisterdiss", label: "Магистерская диссертация"},
    {value: "diplommba", label: "Диплом МВА"},
    {value: "casemba", label: "Кейс Мва"},
    {value: "kursovayteor", label: "Курсовая работа теоретическая"},
    {value: "kursovayaprakt", label: "Курсовая работа практическая"},
    {value: "kursovaya", label: "Курсовой проект"},
    {value: "dorabdiplom", label: "Доработка диплома"},
    {value: "dorabkurs", label: "Доработка курсового"},
    {value: "otchpropra", label: "Отчёт по производственной практике"},
    {value: "otchprepra", label: "Отчет по преддипломной практике"},
    {value: "referat", label: "Реферат"},
    {value: "kontrolka", label: "Контрольная работа"},
    {value: "problem", label: "Решение задач"},
    {value: "anal", label: "Аналитический отчет"},
    {value: "statia", label: "Статья"},
    {value: "test", label: "Тесты"},
    {value: "anwers", label: "Ответы на вопросы"},
    {value: "onlinetest", label: "Онлайн тесты"},
    {value: "esse", label: "Эссе"},
    {value: "planB", label: "Бизнес план"},
    {value: "translation", label: "Перевод текста"},
    {value: "zashitmaterial", label: "Материлы к защите"},
    {value: "otzyv", label: "Отзыв"},
    {value: "review", label: "Рецензия"},
    {value: "annotation", label: "Аннотация"},
    {value: "other", label: "Иная работа"},
    {value: "draft", label: "Чертежи"},
    {value: "aspref", label: "Асп реферат"},
    {value: "disser", label: "Диссертация"},
    {value: "phd", label: "Докторская"},
    {value: "vak", label: "Cтатья ВАК"},
    {value: "presentation", label: "Презентация"},
    {value: "otchetpropra", label: "Отчет по практике"},
    {value: "doklad", label: "Речь/доклад"},
    {value: "slides", label: "Слайды"},
    {value: "razdatok", label: "Раздаток"},
    {value: "plakat A2", label: "Плакаты А2, А3"},
    {value: "titulniy list", label: "Титульный лист"},
    {value: "posledniy list", label: "Последний лист"},
    {value: "AP proverka", label: "АП проверка"},
    {value: "AP sertificat", label: "АП сертификат"},
    {value: "shpora", label: "Шпаргалки"},
    {value: "korrektura", label: "Корректура"}
];

export default  [
    {label: 'Имя', name: "name", type: 'text', placeholder: 'Ваше имя', required: true},
    {label: 'Телефон', name: "phone", type: 'text', placeholder: 'Ваш телефон', required: true},
    {label: 'Почта', name: "email", type: 'email', placeholder: 'email', required: false},
    {label: 'Тема', name: "theme", type: 'text', placeholder: 'Тема работы', required: false},
    {label: 'Вид работы', name: "worktype", type: 'dropdown', options: workTypeOptions, placeholder: 'Укажите подходящий тип работы', required: false},
    {label: 'Предмет', name: "discipline", type: 'text', placeholder: 'Предмет или дисциплина', required: false},
    {label: 'Срок сдачи', name: "deadline", type: 'date', placeholder: 'Укажите срок сдачи работы', required: false},
    {label: 'Объём', name: "size", type: 'text', placeholder: 'Требуемый объём', required: false},
    {label: 'Комментарии', name: "comment", type: 'textarea', placeholder: 'Ваши комментарии', required: false},
    {label: 'Прикрепить Файл', name: "file", type: 'file', placeholder: 'Добавить файл', required: false}
]
